### ISSUE TITLE
Merge your own pull request

### ISSUE THREAD

**Issue by SamerElaila** [facg3/HMICoders#22]
You shouldn't merge your own pull requests
![shdgfksdfsd](https://user-images.githubusercontent.com/19314445/32591805-9b546e74-c529-11e7-997d-9ca13037a147.png)

**Comment by hananqwaider** [comment]
yes samer we know that but  we face a problem in other member laptop  
done ... @SamerElaila

**Comment by hananqwaider** [comment]
we sorry about it
